/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        'space-mono': ['SpaceMono'],
        'cascadia-mono-bold': ['CascadiaMono-Bold'],
        'cascadia-mono-bolditalic': ['CascadiaMono-BoldItalic'],
        'cascadia-mono-extralight': ['CascadiaMono-ExtraLight'],
        'cascadia-mono-extralightitalic': ['CascadiaMono-ExtraLightItalic'],
        'cascadia-mono-italic': ['CascadiaMono-Italic'],
        'cascadia-mono-light': ['CascadiaMono-Light'],
        'cascadia-mono-lightitalic': ['CascadiaMono-LightItalic'],
        'cascadia-mono-medium': ['CascadiaMono-Medium'],
        'cascadia-mono-mediumitalic': ['CascadiaMono-MediumItalic'],
        'cascadia-mono-regular': ['CascadiaMono-Regular'],
        'cascadia-mono-semibold': ['CascadiaMono-SemiBold'],
        'cascadia-mono-semibolditalic': ['CascadiaMono-SemiBoldItalic'],
        'sansation-bold': ['Sansation-Bold'],
        'sansation-bolditalic': ['Sansation-BoldItalic'],
        'sansation-light': ['Sansation-Light'],
        'sansation-lightitalic': ['Sansation-LightItalic'],
        'sansation-regular': ['Sansation-Regular'],
        'sansation-italic': ['Sansation-Italic'],
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
        // Puedes añadir más familias de fuentes aquí si las tienes
      },
    },
  },
  plugins: [],
};